{{- if .Values.podDisruptionBudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "dex.fullname" . }}
  labels:
{{ include "dex.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dex.selectorLabels" . | nindent 6 }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
{{- end -}}