apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex.componentname" (list . "config") }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
