name: CI

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Lint
        run: ct lint

      - name: Docs
        run: |
          make docs
          test "$(git diff --name-only)" == "" \
          || ( printf >&2 "\nREADME files are not up to date (run 'make docs'), differences:\n\n%s\n\n" "$(git diff)" ; exit 1 ; )

      - name: Detect changes
        id: changes
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    if: needs.lint.outputs.changed == 'true'
    strategy:
      matrix:
        kube: ["1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      # See https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
      - name: Determine KinD node image version
        id: node_image
        run: |
          case ${{ matrix.kube }} in
            1.14)
              NODE_IMAGE=kindest/node:v1.14.10@sha256:f8a66ef82822ab4f7569e91a5bccaf27bceee135c1457c512e54de8c6f7219f8 ;;
            1.15)
              NODE_IMAGE=kindest/node:v1.15.12@sha256:b920920e1eda689d9936dfcf7332701e80be12566999152626b2c9d730397a95 ;;
            1.16)
              NODE_IMAGE=kindest/node:v1.16.15@sha256:83067ed51bf2a3395b24687094e283a7c7c865ccc12a8b1d7aa673ba0c5e8861 ;;
            1.17)
              NODE_IMAGE=kindest/node:v1.17.17@sha256:66f1d0d91a88b8a001811e2f1054af60eef3b669a9a74f9b6db871f2f1eeed00 ;;
            1.18)
              NODE_IMAGE=kindest/node:v1.18.19@sha256:7af1492e19b3192a79f606e43c35fb741e520d195f96399284515f077b3b622c ;;
            1.19)
              NODE_IMAGE=kindest/node:v1.19.11@sha256:07db187ae84b4b7de440a73886f008cf903fcf5764ba8106a9fd5243d6f32729 ;;
            1.20)
              NODE_IMAGE=kindest/node:v1.20.7@sha256:cbeaf907fc78ac97ce7b625e4bf0de16e3ea725daf6b04f930bd14c67c671ff9 ;;
            1.21)
              NODE_IMAGE=kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6 ;;
            esac

            echo "::set-output name=image::$NODE_IMAGE"

      - name: Create KinD cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
          node_image: ${{ steps.node_image.outputs.image }}

      - name: Test
        run: ct install
