name: Release

on:
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:
  charts:
    name: Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.0.0
        with:
          charts_dir: charts
          charts_repo_url: https://charts.dexdp.io
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
